"""add campaign tables

Revision ID: 0e76111be7b3
Revises: 5492333b5241
Create Date: 2026-02-23 16:02:09.016086
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e76111be7b3'
down_revision = '5492333b5241'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('target_audience', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('schedule_date', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('audience_source', sa.String(), nullable=False),
    sa.Column('manual_selection', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("audience_source IN ('scraped_leads','customer_upload','manual_selection')", name='ck_campaign_audience_source'),
    sa.CheckConstraint("status IN ('draft','scheduled','active','paused','failed','completed')", name='ck_campaign_status'),
    sa.CheckConstraint('budget IS NULL OR budget >= 0', name='ck_campaign_budget_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaign_org_created', 'campaigns', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_campaign_org_status', 'campaigns', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_campaigns_campaign_name'), 'campaigns', ['campaign_name'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_table('campaign_metrics',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.Column('opened', sa.Integer(), nullable=False),
    sa.Column('clicked', sa.Integer(), nullable=False),
    sa.Column('converted', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('cpa', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('clicked >= 0', name='ck_campaign_metrics_clicked_non_negative'),
    sa.CheckConstraint('conversion_rate >= 0', name='ck_campaign_metrics_conversion_rate_non_negative'),
    sa.CheckConstraint('converted >= 0', name='ck_campaign_metrics_converted_non_negative'),
    sa.CheckConstraint('cost >= 0', name='ck_campaign_metrics_cost_non_negative'),
    sa.CheckConstraint('cpa >= 0', name='ck_campaign_metrics_cpa_non_negative'),
    sa.CheckConstraint('ctr >= 0', name='ck_campaign_metrics_ctr_non_negative'),
    sa.CheckConstraint('impressions >= 0', name='ck_campaign_metrics_impressions_non_negative'),
    sa.CheckConstraint('opened >= 0', name='ck_campaign_metrics_opened_non_negative'),
    sa.CheckConstraint('sent >= 0', name='ck_campaign_metrics_sent_non_negative'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_index(op.f('ix_campaign_metrics_campaign_id'), 'campaign_metrics', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_metrics_org_campaign', 'campaign_metrics', ['organization_id', 'campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_metrics_organization_id'), 'campaign_metrics', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_metrics_organization_id'), table_name='campaign_metrics')
    op.drop_index('ix_campaign_metrics_org_campaign', table_name='campaign_metrics')
    op.drop_index(op.f('ix_campaign_metrics_campaign_id'), table_name='campaign_metrics')
    op.drop_table('campaign_metrics')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_name'), table_name='campaigns')
    op.drop_index('ix_campaign_org_status', table_name='campaigns')
    op.drop_index('ix_campaign_org_created', table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###