"""initial schema

Revision ID: 5492333b5241
Revises: 
Create Date: 2026-02-23 15:37:37.839151
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5492333b5241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###