"""add strategy persistence tables

Revision ID: 9e226f34648f
Revises: fdf702f7e19b
Create Date: 2026-02-24 10:31:54.130237
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e226f34648f'
down_revision = 'fdf702f7e19b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.create_index('ix_strategies_org_created', 'strategies', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_strategies_org_status', 'strategies', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_strategies_organization_id'), 'strategies', ['organization_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('business_profile_json', sa.JSON(), nullable=True),
    sa.Column('additional_context', sa.Text(), nullable=True),
    sa.Column('strategy_output_json', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version_no', name='uq_strategy_version')
    )
    op.create_index(op.f('ix_strategy_versions_id'), 'strategy_versions', ['id'], unique=False)
    op.create_index('ix_strategy_versions_org_generated_desc', 'strategy_versions', ['organization_id', sa.literal_column('generated_at DESC')], unique=False)
    op.create_index(op.f('ix_strategy_versions_organization_id'), 'strategy_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.create_index('ix_strategy_versions_strategy_version_desc', 'strategy_versions', ['strategy_id', sa.literal_column('version_no DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategy_versions_strategy_version_desc', table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_organization_id'), table_name='strategy_versions')
    op.drop_index('ix_strategy_versions_org_generated_desc', table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_strategies_organization_id'), table_name='strategies')
    op.drop_index('ix_strategies_org_status', table_name='strategies')
    op.drop_index('ix_strategies_org_created', table_name='strategies')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')
    # ### end Alembic commands ###