"""add lead enrichment tables

Revision ID: fdf702f7e19b
Revises: 0e76111be7b3
Create Date: 2026-02-23 16:55:33.629354
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf702f7e19b'
down_revision = '0e76111be7b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('original_count', sa.Integer(), nullable=False),
    sa.Column('enriched_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('enriched_count >= 0', name='ck_enrichment_task_enriched_count_non_negative'),
    sa.CheckConstraint('original_count >= 0', name='ck_enrichment_task_original_count_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enrichment_task_org_created', 'enrichment_tasks', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_enrichment_task_org_status', 'enrichment_tasks', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_enrichment_tasks_id'), 'enrichment_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_enrichment_tasks_organization_id'), 'enrichment_tasks', ['organization_id'], unique=False)
    op.create_table('lead_scrape_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('requested_sources', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source_results', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_results IS NULL OR max_results > 0', name='ck_lead_scrape_task_max_results_positive'),
    sa.CheckConstraint('radius IS NULL OR radius >= 0', name='ck_lead_scrape_task_radius_non_negative'),
    sa.CheckConstraint('total_found >= 0', name='ck_lead_scrape_task_total_found_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_scrape_task_org_created', 'lead_scrape_tasks', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_lead_scrape_task_org_status', 'lead_scrape_tasks', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_lead_scrape_tasks_id'), 'lead_scrape_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_lead_scrape_tasks_organization_id'), 'lead_scrape_tasks', ['organization_id'], unique=False)
    op.create_table('enrichment_rows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('original_data', sa.JSON(), nullable=False),
    sa.Column('enriched_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('row_index >= 0', name='ck_enrichment_row_row_index_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['enrichment_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'row_index', name='uq_enrichment_row_task_index')
    )
    op.create_index('ix_enrichment_row_org_task', 'enrichment_rows', ['organization_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_enrichment_rows_id'), 'enrichment_rows', ['id'], unique=False)
    op.create_index(op.f('ix_enrichment_rows_organization_id'), 'enrichment_rows', ['organization_id'], unique=False)
    op.create_index(op.f('ix_enrichment_rows_task_id'), 'enrichment_rows', ['task_id'], unique=False)
    op.create_table('lead_scrape_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('GITHUB', 'GOOGLE_MAPS', 'LINKEDIN', 'VOLZA', name='leadsource'), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['lead_scrape_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_scrape_result_org_source', 'lead_scrape_results', ['organization_id', 'source'], unique=False)
    op.create_index('ix_lead_scrape_result_org_task', 'lead_scrape_results', ['organization_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_lead_scrape_results_id'), 'lead_scrape_results', ['id'], unique=False)
    op.create_index(op.f('ix_lead_scrape_results_organization_id'), 'lead_scrape_results', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lead_scrape_results_source'), 'lead_scrape_results', ['source'], unique=False)
    op.create_index(op.f('ix_lead_scrape_results_task_id'), 'lead_scrape_results', ['task_id'], unique=False)
    op.create_table('lead_source_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('GITHUB', 'GOOGLE_MAPS', 'LINKEDIN', 'VOLZA', name='leadsource'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('leads_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('leads_count >= 0', name='ck_lead_source_run_leads_count_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['lead_scrape_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'source', name='uq_lead_source_run_task_source')
    )
    op.create_index('ix_lead_source_run_org_task', 'lead_source_runs', ['organization_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_lead_source_runs_id'), 'lead_source_runs', ['id'], unique=False)
    op.create_index(op.f('ix_lead_source_runs_organization_id'), 'lead_source_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lead_source_runs_task_id'), 'lead_source_runs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_source_runs_task_id'), table_name='lead_source_runs')
    op.drop_index(op.f('ix_lead_source_runs_organization_id'), table_name='lead_source_runs')
    op.drop_index(op.f('ix_lead_source_runs_id'), table_name='lead_source_runs')
    op.drop_index('ix_lead_source_run_org_task', table_name='lead_source_runs')
    op.drop_table('lead_source_runs')
    op.drop_index(op.f('ix_lead_scrape_results_task_id'), table_name='lead_scrape_results')
    op.drop_index(op.f('ix_lead_scrape_results_source'), table_name='lead_scrape_results')
    op.drop_index(op.f('ix_lead_scrape_results_organization_id'), table_name='lead_scrape_results')
    op.drop_index(op.f('ix_lead_scrape_results_id'), table_name='lead_scrape_results')
    op.drop_index('ix_lead_scrape_result_org_task', table_name='lead_scrape_results')
    op.drop_index('ix_lead_scrape_result_org_source', table_name='lead_scrape_results')
    op.drop_table('lead_scrape_results')
    op.drop_index(op.f('ix_enrichment_rows_task_id'), table_name='enrichment_rows')
    op.drop_index(op.f('ix_enrichment_rows_organization_id'), table_name='enrichment_rows')
    op.drop_index(op.f('ix_enrichment_rows_id'), table_name='enrichment_rows')
    op.drop_index('ix_enrichment_row_org_task', table_name='enrichment_rows')
    op.drop_table('enrichment_rows')
    op.drop_index(op.f('ix_lead_scrape_tasks_organization_id'), table_name='lead_scrape_tasks')
    op.drop_index(op.f('ix_lead_scrape_tasks_id'), table_name='lead_scrape_tasks')
    op.drop_index('ix_lead_scrape_task_org_status', table_name='lead_scrape_tasks')
    op.drop_index('ix_lead_scrape_task_org_created', table_name='lead_scrape_tasks')
    op.drop_table('lead_scrape_tasks')
    op.drop_index(op.f('ix_enrichment_tasks_organization_id'), table_name='enrichment_tasks')
    op.drop_index(op.f('ix_enrichment_tasks_id'), table_name='enrichment_tasks')
    op.drop_index('ix_enrichment_task_org_status', table_name='enrichment_tasks')
    op.drop_index('ix_enrichment_task_org_created', table_name='enrichment_tasks')
    op.drop_table('enrichment_tasks')
    # ### end Alembic commands ###